// Generated by CoffeeScript 1.3.3
var express, path;

express = require('express');

path = require('path');

module.exports = function(parent) {
  var wiki;
  wiki = express();
  wiki.set('views', path.join(__dirname, "views"));
  return parent.use(wiki);
};
